### ISSUE TITLE
undefined method `jcropper_admin_project_image_path'

### ISSUE THREAD

**Issue by fernahh** [Ricardonacif/active_admin_jcrop#10]
I'm developing a application with:
- Rails 4.2.0
- Paperclip 4.2.1
- ActiveAdmin 1.0.0

Added the structure below for my model:

``` ruby
ActiveAdmin.register ProjectImage do

  jcropable

  form do |f|
    f.inputs do
      f.input :image, as: :jcropable
      f.input :caption
    end
    f.actions
  end

end
```

The error is this:

```
undefined method `jcropper_admin_project_image_path`
```

How can I fix this?

Thanks!

**Comment by fernahh** [comment]
This method is being called at this line: https://github.com/Ricardonacif/active_admin_jcrop/blob/master/app/views/active_admin_jcrop/_jcrop_modal.html.erb#L10

My problem is that I have my image model as a nested resource.

**Comment by Ricardonacif** [comment]
Hey Luis,

I believe The gem doesn't support nested models yet. I'm currently
traveling (to a Ruby Conference, lol) and I might take a look at it
sometime next week. But if you want to do a pull request before, feel free.

Thanks,

**Comment by fernahh** [comment]
Thanks by reply, @Ricardonacif.

@rwillrich I belive that you can help. This gem is useful for our projects! :)

**Comment by rwillrich** [comment]
I'll see what I can do!

**Comment by AliUz** [comment]
I would also love to see support for nested models, I am having the same issue :)

**Comment by Ricardonacif** [comment]
Guys, I'm really busy these days and I didn't have time to implement support for nested models. I guess I'll have time to do it only next month, so if anyone wants to work on that, feel free and let us know here.

Thanks,
