### ISSUE TITLE
Polluting ActiveRecord::Base with crop_* methods

### ISSUE THREAD

**Issue by glampr** [Ricardonacif/active_admin_jcrop#11]
Are you sure that this is the best approach?
I think that it is should be left up to the application to include the `ActiveAdminJcrop::Orm::Extension` to the models that require this behaviour, eg: 

``` ruby
class Photo
  include ActiveAdminJcrop::Orm::Extension
end
```

This way all models in the app end up having the crop_\* methods, which can lead to problems.
For example if my application, my Photo model has already the crop_\* attributes as fields in the database, so adding your gem ends up with an error: 
`crop_* is defined by Active Record.
Check to make sure that you don't have an attribute or method with the same name.`
Of course what I'm suggesting would still create this problem if I included the module in my Photo class, but I could make it to work by not including your module and just defining `active_admin_cropping?` and `active_admin_crop!` directly into my model.

Anyway, this suggest a breaking change to your DSL, so not sure if you want to go that way. Just want to share my thoughts :)

**Comment by Ricardonacif** [comment]
Hey @glampr, nice suggestion. I'll be busy during the next weeks and won't be able to work on that, but feel free to create a pull request (don't forget to change the Readme as well).

Thanks,
