### ISSUE TITLE
Rails 3.2 undefined method jcropper_admin_[model]_path line #10

### ISSUE THREAD

**Issue by jkippels** [Ricardonacif/active_admin_jcrop#13]
Hello,

I was trying this gem for my active admin interface in Rails 3.2 , Ruby 2.0.0 and I get following error:

`undefined method jcropper_admin_[model]_path' for #<#<Class:0x007feaa80aef48>:0x007feaa80ad300>
in line #10 gems/active_admin_jcrop-0.0.9/app/views/active_admin_jcrop/_jcrop_modal.html.erb`

 `jcropper_url: send("jcropper_#{ActiveAdmin.application.default_namespace.to_s}_#{object.class.to_s.demodulize.underscore}_path", object)`

Is it possible to fix this pathing? Thank you very much.

'Edit' I forgot to add jcropable infront of the form sorry fixed that issue, but I am still getting the error `Uncaught TypeError: image.Jcrop is not a function`, when pressing crop image, in crop.modal.js : 96.

Are there any dependencies on crop.modal.js which require Jcrop to load first
 `<script src="/assets/active_admin_jcrop/crop_modal.js" type="text/javascript"></script>
    <script src="/assets/active_admin_jcrop/jquery.color.js" type="text/javascript"></script>
    <script src="/assets/active_admin_jcrop/jquery.Jcrop.min.js" type="text/javascript"></script>` ?

**Comment by Ricardonacif** [comment]
hey @jkippels, can you please try using the latest version (from master) of the gem? On the gemfile, just do:
```
gem 'active_admin_jcrop', :github => 'Ricardonacif/active_admin_jcrop'
```

**Comment by jensJJ** [comment]
Hi, I just tried this, but still get the same error when pressing crop image. ` image.Jcrop(options);`in `crop.modal.js line 96`.
