### ISSUE TITLE
Use it for different namespaces

### ISSUE THREAD

**Issue by ivanelrey** [Ricardonacif/active_admin_jcrop#21]
I have configured **active_admin** for different namespaces. But crop uses only the default one how can I use it for different active_admin namespaces?

**Comment by Ricardonacif** [comment]
@ivanelrey you can change the code on this file https://github.com/Ricardonacif/active_admin_jcrop/blob/master/lib/active_admin_jcrop/view_helpers.rb . You can either fork it and use your fork or add the option to specify namespace and contribute to the gem with a PR 👍 

Let me know if you need any help!
