### ISSUE TITLE
register_javascript deprecation

### ISSUE THREAD

**Issue by yourtallness** [Ricardonacif/active_admin_jcrop#22]
The `register_javascript` function that is used in the `railtie.rb` is deprecated in activeadmin 1.4.3:

> DEPRECATION WARNING: Active Admin: The `register_javascript` config is deprecated and will be removed
> in v2. Import your "active_admin_jcrop/crop_modal" javascript in the active_admin.js.

**Comment by Ricardonacif** [comment]
Hey @yourtallness

Sorry for the delay! I'm no longer involved with ActiveAdmin or even Rails (unfortunately 😢 ). Could you come up with a patch for this deprecation?
