### ISSUE TITLE
Ajax request not working

### ISSUE THREAD

**Issue by zeshan9128** [Ricardonacif/active_admin_jcrop#24]
@Ricardonacif I followed the documentation provided by you with paper clip but in my scenario its not sending ajax request. When will it send the ajax request ? I also see the "Save Cropped Image" button in inspect code but that's also not appearing.

**Comment by Ricardonacif** [comment]
Hey Zeshan,

This gem has not being updated for 7 years. I'm sorry but I can't provide support for it anymore, and I believe it won't work with any current version of Rails or Active Admin. It's open for PRs tho so if you figured it out please let me know.
